name: 'GT Translate'
description: 'Github Action integration for gtx-cli translate'
author: 'generaltranslation'
branding:
  icon: 'globe'
  color: 'blue'

inputs:
  gt_api_key:
    description: 'API key for General Translation cloud service'
    required: true
  gt_project_id:
    description: 'Project ID for the translation service'
    required: true
  config:
    description: 'Filepath to config file, by default gt.config.json'
    required: false
  version_id:
    description: 'Version ID for the translation service'
    required: false
  tsconfig:
    description: 'Path to jsconfig or tsconfig file'
    required: false
  dictionary:
    description: 'Path to dictionary file'
    required: false
  src:
    description: 'Filepath to directory containing the app source code'
    required: false
  default_language:
    description: 'Default locale (e.g., en)'
    required: false
  locales:
    description: 'Space-separated list of locales (e.g., en fr es)'
    required: false
  inline:
    description: 'Include inline <T> tags in addition to dictionary file'
    required: false
    default: 'true'
  ignore_errors:
    description: 'Ignore errors encountered while scanning for <T> tags'
    required: false
    default: 'false'
  dry_run:
    description: 'Dry run, does not send updates to General Translation API'
    required: false
    default: 'false'
  timeout:
    description: 'Timeout in seconds for waiting for updates to be deployed to the CDN'
    required: false
  experimental_localize_static_urls:
    description: 'Run script to localize all urls in content files'
    required: false
    default: 'false'
  experimental_hide_default_locale:
    description: 'Hide the default locale from the path when localizing static locales'
    required: false
    default: 'false'
  experimental_flatten_json_files:
    description: 'Flatten json files into a single file'
    required: false
    default: 'false'
  github_token:
    description: 'GitHub token for creating pull requests'
    required: false
    default: ${{ github.token }}
  version:
    description: 'gtx-cli version to use'
    required: false
    default: 'latest'
  pr_branch:
    description: 'Branch name for pull requests'
    required: false
    default: 'gt-translate/${{ github.ref_name }}'
  pr_title:
    description: 'Title for pull requests'
    required: false
    default: '[ci] translate'
  pr_body:
    description: 'Body for pull requests'
    required: false
    default: |
      ## 🌍 GT Translate Update

      This is an **automated pull request** created by GT Translate.

      ### What's included
      - Translation updates based on your latest changes
      - Updated dictionary and localized content

      ### Next steps
      1. Review the translations for accuracy
      2. Test the changes in your development environment  
      3. Merge when ready to deploy translated content

      ### Commit
      ${{ github.event.head_commit.author.name || 'Unknown' }}
      ${{ github.event.head_commit.author.email || 'unknown@example.com' }}
      ${{ github.event.head_commit.author.date || 'Unknown date' }}
      ${{ github.event.head_commit.message || 'No commit message available' }}

      ---
      *Generated automatically by GT Translate*

runs:
  using: 'node20'
  main: 'dist/index.js'
